### ISSUE TITLE
Erro quando há um arquivo temporário no diretório antes do commit

### ISSUE THREAD

**Issue by mirnacarelli** [daltonserey/tst#3]
```
$ tst commit2
Traceback (most recent call last):
  File "/home/mirna/.tst/commands/tst-commit2", line 269, in <module>
    main()
  File "/home/mirna/.tst/commands/tst-commit2", line 224, in main
    activity, unknown = tst.read_activity(tstjson)
  File "/home/mirna/.tst/bin/tstlib.py", line 363, in read_activity
    unknown_files = [f for f in activity_files if f not in tstjson['files']]
KeyError: u'files'
mirna@splab:~/Dropbox/Doutorado Mirna/tst/mc1
$ ls
mc1.yaml  mc1.yaml~  tst.json
mirna@splab:~/Dropbox/Doutorado Mirna/tst/mc1
$ rm -rf mc1.yaml~
mirna@splab:~/Dropbox/Doutorado Mirna/tst/mc1
$ tst commit2
Commmit finished.
0.1.0
```

**Comment by daltonserey** [comment]
@mirnacarelli Ok. Só registrando. Isso só ocorre quando a atividade é nova e nunca foi _commitada_ antes.
